site_name: Construindo APIs robustas
theme:
  name: material
  language: pt
  palette: 
    - scheme: default
      primary: brown
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate 
      primary: brown
      accent: amber
      toggle:
        icon: material/lightbulb 
        name: Switch to light mode
  icon:
    logo: material/cart
  favicon: imgs/favicon.ico
  features:
    - content.tabs.link
markdown_extensions:
  - pymdownx.emoji
  - pymdownx.tasklist:
     custom_checkbox: true
  - pymdownx.superfences
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - md_in_html
repo_name: cassiobotaro/construindo-apis-robustas
repo_url: https://github.com/cassiobotaro/construindo-apis-robustas

nav:
  - â–¶ï¸ IntroduÃ§Ã£o: index.md
  - ğŸ’­ Planejando o que serÃ¡ desenvolvido: planejando.md
  - ğŸ§° Escolhendo as melhores ferramentas: ferramentas.md
  - ğŸ“ Iniciando o projeto: projeto.md
  - ğŸ‘‹ OlÃ¡ API: ola_api.md
  - ğŸ¤ IntegraÃ§Ã£o com serviÃ§os externos: externos.md
  - ğŸ“œ DocumentaÃ§Ã£o: docs.md
  - âœ”ï¸ IntegraÃ§Ã£o contÃ­nua: continua.md
  - ğŸ† Desafios: desafios.md
  - ğŸ† Processos assÃ­ncronos: assincrono.md
  - ğŸ”Œ Circuit breaker: breaker.md
  - ğŸ¦¸ TÃ©cnicas (um pouco mais avanÃ§adas): avancadas.md
  - ğŸ“‘ ReferÃªncias e Dicas: referencias.md

